apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - safety_v1alpha1_terminationpolicy_report-only.yaml
  - safety_v1alpha1_terminationpolicy_remediation.yaml
  - safety_v1alpha1_remediationapproval_dry-run.yaml
