//go:build !ignore_autogenerated

// Copyright 2026 The ExitGuard Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Conditions) DeepCopyInto(out *Conditions) {
	{
		in := &in
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in Conditions) DeepCopy() Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerReference) DeepCopyInto(out *ControllerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerReference.
func (in *ControllerReference) DeepCopy() *ControllerReference {
	if in == nil {
		return nil
	}
	out := new(ControllerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionIncident) DeepCopyInto(out *DeletionIncident) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionIncident.
func (in *DeletionIncident) DeepCopy() *DeletionIncident {
	if in == nil {
		return nil
	}
	out := new(DeletionIncident)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeletionIncident) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionIncidentList) DeepCopyInto(out *DeletionIncidentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeletionIncident, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionIncidentList.
func (in *DeletionIncidentList) DeepCopy() *DeletionIncidentList {
	if in == nil {
		return nil
	}
	out := new(DeletionIncidentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeletionIncidentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionIncidentSpec) DeepCopyInto(out *DeletionIncidentSpec) {
	*out = *in
	out.Target = in.Target
	in.FirstObservedTime.DeepCopyInto(&out.FirstObservedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionIncidentSpec.
func (in *DeletionIncidentSpec) DeepCopy() *DeletionIncidentSpec {
	if in == nil {
		return nil
	}
	out := new(DeletionIncidentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionIncidentStatus) DeepCopyInto(out *DeletionIncidentStatus) {
	*out = *in
	if in.ActivePolicyRef != nil {
		in, out := &in.ActivePolicyRef, &out.ActivePolicyRef
		*out = new(PolicyReference)
		**out = **in
	}
	if in.DeletionTimestamp != nil {
		in, out := &in.DeletionTimestamp, &out.DeletionTimestamp
		*out = (*in).DeepCopy()
	}
	if in.LastObservedTime != nil {
		in, out := &in.LastObservedTime, &out.LastObservedTime
		*out = (*in).DeepCopy()
	}
	if in.ActionEvidenceTime != nil {
		in, out := &in.ActionEvidenceTime, &out.ActionEvidenceTime
		*out = (*in).DeepCopy()
	}
	if in.ActionEvidenceExpiresTime != nil {
		in, out := &in.ActionEvidenceExpiresTime, &out.ActionEvidenceExpiresTime
		*out = (*in).DeepCopy()
	}
	if in.ResolvedTime != nil {
		in, out := &in.ResolvedTime, &out.ResolvedTime
		*out = (*in).DeepCopy()
	}
	in.TargetSnapshot.DeepCopyInto(&out.TargetSnapshot)
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RecommendedActions != nil {
		in, out := &in.RecommendedActions, &out.RecommendedActions
		*out = make([]RemediationAction, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionIncidentStatus.
func (in *DeletionIncidentStatus) DeepCopy() *DeletionIncidentStatus {
	if in == nil {
		return nil
	}
	out := new(DeletionIncidentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicy) DeepCopyInto(out *DiagnosisPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicy.
func (in *DiagnosisPolicy) DeepCopy() *DiagnosisPolicy {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FinalizerOwner) DeepCopyInto(out *FinalizerOwner) {
	*out = *in
	out.ControllerRef = in.ControllerRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FinalizerOwner.
func (in *FinalizerOwner) DeepCopy() *FinalizerOwner {
	if in == nil {
		return nil
	}
	out := new(FinalizerOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	if in.ResourceRef != nil {
		in, out := &in.ResourceRef, &out.ResourceRef
		*out = new(TargetReference)
		**out = **in
	}
	if in.ControllerRef != nil {
		in, out := &in.ControllerRef, &out.ControllerRef
		*out = new(ControllerReference)
		**out = **in
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectIdentityReference) DeepCopyInto(out *ObjectIdentityReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectIdentityReference.
func (in *ObjectIdentityReference) DeepCopy() *ObjectIdentityReference {
	if in == nil {
		return nil
	}
	out := new(ObjectIdentityReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyReference) DeepCopyInto(out *PolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyReference.
func (in *PolicyReference) DeepCopy() *PolicyReference {
	if in == nil {
		return nil
	}
	out := new(PolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationAction) DeepCopyInto(out *RemediationAction) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationAction.
func (in *RemediationAction) DeepCopy() *RemediationAction {
	if in == nil {
		return nil
	}
	out := new(RemediationAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationApproval) DeepCopyInto(out *RemediationApproval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationApproval.
func (in *RemediationApproval) DeepCopy() *RemediationApproval {
	if in == nil {
		return nil
	}
	out := new(RemediationApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationApproval) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationApprovalList) DeepCopyInto(out *RemediationApprovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemediationApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationApprovalList.
func (in *RemediationApprovalList) DeepCopy() *RemediationApprovalList {
	if in == nil {
		return nil
	}
	out := new(RemediationApprovalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationApprovalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationApprovalSpec) DeepCopyInto(out *RemediationApprovalSpec) {
	*out = *in
	out.IncidentRef = in.IncidentRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationApprovalSpec.
func (in *RemediationApprovalSpec) DeepCopy() *RemediationApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationApprovalStatus) DeepCopyInto(out *RemediationApprovalStatus) {
	*out = *in
	if in.StartedTime != nil {
		in, out := &in.StartedTime, &out.StartedTime
		*out = (*in).DeepCopy()
	}
	if in.CompletedTime != nil {
		in, out := &in.CompletedTime, &out.CompletedTime
		*out = (*in).DeepCopy()
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(RemediationAction)
		**out = **in
	}
	if in.Attempts != nil {
		in, out := &in.Attempts, &out.Attempts
		*out = make([]RemediationAttempt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationApprovalStatus.
func (in *RemediationApprovalStatus) DeepCopy() *RemediationApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationAttempt) DeepCopyInto(out *RemediationAttempt) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationAttempt.
func (in *RemediationAttempt) DeepCopy() *RemediationAttempt {
	if in == nil {
		return nil
	}
	out := new(RemediationAttempt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicy) DeepCopyInto(out *RemediationPolicy) {
	*out = *in
	if in.AllowedFinalizers != nil {
		in, out := &in.AllowedFinalizers, &out.AllowedFinalizers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ApprovalTTL = in.ApprovalTTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicy.
func (in *RemediationPolicy) DeepCopy() *RemediationPolicy {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
	out.ResolvedIncidentTTL = in.ResolvedIncidentTTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRule) DeepCopyInto(out *TargetRule) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectSelector != nil {
		in, out := &in.ObjectSelector, &out.ObjectSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludedNamespaces != nil {
		in, out := &in.ExcludedNamespaces, &out.ExcludedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRule.
func (in *TargetRule) DeepCopy() *TargetRule {
	if in == nil {
		return nil
	}
	out := new(TargetRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSnapshot) DeepCopyInto(out *TargetSnapshot) {
	*out = *in
	if in.MetadataFinalizers != nil {
		in, out := &in.MetadataFinalizers, &out.MetadataFinalizers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceFinalizers != nil {
		in, out := &in.NamespaceFinalizers, &out.NamespaceFinalizers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSnapshot.
func (in *TargetSnapshot) DeepCopy() *TargetSnapshot {
	if in == nil {
		return nil
	}
	out := new(TargetSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminationPolicy) DeepCopyInto(out *TerminationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminationPolicy.
func (in *TerminationPolicy) DeepCopy() *TerminationPolicy {
	if in == nil {
		return nil
	}
	out := new(TerminationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TerminationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminationPolicyList) DeepCopyInto(out *TerminationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TerminationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminationPolicyList.
func (in *TerminationPolicyList) DeepCopy() *TerminationPolicyList {
	if in == nil {
		return nil
	}
	out := new(TerminationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TerminationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminationPolicySpec) DeepCopyInto(out *TerminationPolicySpec) {
	*out = *in
	if in.TargetRules != nil {
		in, out := &in.TargetRules, &out.TargetRules
		*out = make([]TargetRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.TerminationAge = in.TerminationAge
	out.Diagnosis = in.Diagnosis
	if in.FinalizerOwners != nil {
		in, out := &in.FinalizerOwners, &out.FinalizerOwners
		*out = make([]FinalizerOwner, len(*in))
		copy(*out, *in)
	}
	in.Remediation.DeepCopyInto(&out.Remediation)
	out.Retention = in.Retention
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminationPolicySpec.
func (in *TerminationPolicySpec) DeepCopy() *TerminationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(TerminationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TerminationPolicyStatus) DeepCopyInto(out *TerminationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastValidatedTime != nil {
		in, out := &in.LastValidatedTime, &out.LastValidatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TerminationPolicyStatus.
func (in *TerminationPolicyStatus) DeepCopy() *TerminationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(TerminationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
