apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/safety.exitguard.io_deletionincidents.yaml
- bases/safety.exitguard.io_remediationapprovals.yaml
- bases/safety.exitguard.io_terminationpolicies.yaml
